### ISSUE TITLE
Handle lists and other containers in properties and method call results

### ISSUE THREAD

**Issue by nthiery** [sagemath/sage-explorer#1]
Let's assume that a property (or result of a method call) of the object being explored consists of a list/tuple/set/frozen_set/dictionary L. Then we would want:

- [x] L to be nicely displayed (e.g. as {x,y,z} for a set)
- [x] each object of L to be clickable to further explore it

**Comment by zerline** [comment]
This looks like #5

**Comment by nthiery** [comment]
This could indeed be made into a subitem of #5.

**Comment by zerline** [comment]
Try to make list items clickable.

**Comment by zerline** [comment]
Except for dictionaries: fixed by https://github.com/sagemath/sage-explorer/commit/e368740a016c0ac219c0f3b1135bffd00b0f7614

We will now find a way to explore the list/tuple/set by itself .. another issue.
