### ISSUE TITLE
Default layout

### ISSUE THREAD

**Issue by nthiery** [sagemath/sage-explorer#15]
Design a nice layout (with user feedback!) for the explore widget

Some questions:
- Location of the "back button"
- Location of the various zones
- Widget title?
- Some alignment between methods and properties?
- Location of the method results

Source of inspirations:
- Macaulay's  javascript graph visualization tool (see #14).
- lmfdb.org (they have a lot of (user) experience in terms of design).

**Comment by zerline** [comment]
Thanks to Nathan Carter's inspiration, there is now a new design in the `new_design` branch.
* The title box is now more visible.
* We now habe a clean table for properties
* There would be no back button, but we will use a dropdown for the history.
* The output comes below the inputs
* A question arises: where to put the help text, and possibly the methods hierarchical sorting.

**Comment by zerline** [comment]
outdated. @nthiery can we close this issue?
