### ISSUE TITLE
Rename 'attributes' to 'properties' (in the code)

### ISSUE THREAD

**Issue by zerline** [sagemath/sage-explorer#16]
In the python code, rename 'attributes' to 'properties' , to follow the wording on the widget itself.

**Comment by nthiery** [comment]
We should indeed be eventually consistent. We may want to postpone that a bit though, as the terminology is still in flux, and we may still end up choosing some other name. For example, in the Macaulay widget they use "numerical invariants/boolean tests"; in lmfdb it's invariants/properties.
