### ISSUE TITLE
Upon switching to a new object, reset the help zone to the help about the object

### ISSUE THREAD

**Issue by nthiery** [sagemath/sage-explorer#18]
Example scenario:
1. Start the explorer: `explore(Partition([3,2,2]))`
2. Select the method `block` from the Partitions class; it displays the Run/Help tab.
3. Click on the Element of property (Partitions)
Currently the doc of `block` remains displayed; instead we would want it to be replaced by the doc of Partitions.

Thanks :-)

(as an aside: in the above scenario, there is a large empty zone between the list of methods on the left and the Run/Help tab of `block` on the right).

**Comment by zerline** [comment]
Commit https://github.com/sagemath/sage-explorer/commit/21f25fc42046c9fdcae112e78498069cf09d7c16
