### ISSUE TITLE
API to configure properties at runtime

### ISSUE THREAD

**Issue by nthiery** [sagemath/sage-explorer#20]
At this stage, we don't know what will be the preferred way for configuring properties to be displayed:
editing the yaml configuration file, getting the data from semantic information in Sage, ... Hence we should support a programmatic way of configuring them, so that users can explore and try new things.
This will be useful for #3 too.

Something like:
```
sage_explorer.add_property('category', in=Sets)
sage_explorer.add_property('genus', isinstance=sage....foo.Foo)
...
```

As a side effect, this would allow to go around  the current limitation in the configuration file
syntax that supports only one entry with a given name.

**Comment by zerline** [comment]
Closed in favor of #45
