### ISSUE TITLE
UI for values displayed in the explorer

### ISSUE THREAD

**Issue by nthiery** [sagemath/sage-explorer#24]
Design some uniform UI for values displayed in the explorer, to enable the following actions
- use as main value for this explorer (analog of following a link in a browser): typically left click?
- configure rich display (through an item in a menu brought up by right click?)
  See also #5, #23 
- inject in the global name space, under some user-chosen variable name, so that the user can manipulate it from the cells? Not as nice, but the user can already explore the value, and then fetch it from the explorer.
- open a mini-notebook here to compute with that value???

**Comment by zerline** [comment]
Partly done, partly superseded by #29
