### ISSUE TITLE
special methods in the method list

### ISSUE THREAD

**Issue by nthiery** [sagemath/sage-explorer#34]
Currently, methods starting with _ appear early in the list (if not first if there is no uppercased method). Usually these methods are less interesting. Instead, put
- first normal methods `foo`
- then Sage special methods with `_foo_`
- then Python special methods with `__foo__`
- then "private" methods starting with `_foo`

**Comment by zerline** [comment]
We finally decided to have no private method in the list by default. Therefore, I'm closing this issue _for now_. Cf commit # 9b4e9b86ac86
