### ISSUE TITLE
Exploring catalogs

### ISSUE THREAD

**Issue by zerline** [sagemath/sage-explorer#42]
Exploring all catalogs in our `_catalogs.py`

**Comment by zerline** [comment]
Possibly fixed now. Please review 6a80df6fb682e !

**Comment by zerline** [comment]
For `explore()`:
Shall we define a default catalog, a catalog of catalog?

**Comment by nthiery** [comment]
> Shall we define a default catalog, a catalog of catalog?

A catalog of catalogs sounds quite natural indeed; well worth trying!

**Comment by zerline** [comment]
Should be fixed now. At least since dfe03a9a315e288ce3c
