### ISSUE TITLE
Add __repr__ method to SageExplorer

### ISSUE THREAD

**Issue by nthiery** [sagemath/sage-explorer#46]
Current:

    sage: from sage_explorer import explore
    sage: explore(3)
    SageExplorer(children=(VBox(children=(ExplorerTitle(children=(MathTitle(value='Exploring: 3', ...)

Proposal:

    sage: explore(3)
    SageExplorer(3)

Variant:

    SageExplorer for 3, with properties "foo", "bar", "baz"

Side benefits: this could be used for testing.

**Comment by zerline** [comment]
Just did the simplest one with 15c766e2a8ab7e31

For the second: until now properties names list is not a ```SageExplorer``` attribute.

The list of "explorables" (ie objects, not just strings) is an ```ExplorerProperties``` attribute. So the code could be like:

```
w = explore(42)
[e.name for e in w.propsbox.explorables]
```

**Comment by nthiery** [comment]
> Just did the simplest one with 15c766e2a8ab7e31

Thanks!

> For the second: until now properties names list is not a ```SageExplorer``` attribute.
> The list of "explorables" (ie objects, not just strings) is an ```ExplorerProperties``` attribute. So the code could be like:
> 
> ```
> w = explore(42)
> [e.name for e in w.propsbox.explorables]
> ```

Sounds good.
