### ISSUE TITLE
Sync back the main display widget and the explorer

### ISSUE THREAD

**Issue by nthiery** [sagemath/sage-explorer#6]
When the user uses the widget in the main display area to modify the value of the object,
this modification should be synced back to the explorer value.

Potential implementation:
- Make the value of the widget a traitlet
- Make the value of the explorer a traitlet
- link the former to the latter

**Comment by zerline** [comment]
Should have been fixed by commit # https://github.com/sagemath/sage-explorer/commit/7064c50ee0c47c67df3fa3f76015cd09ce723005
