### ISSUE TITLE
Remove "----" in the list of methods

### ISSUE THREAD

**Issue by nthiery** [sagemath/sage-explorer#7]
This uses quite some space; alternatively, move it at the end of the list

**Comment by zerline** [comment]
"----" is a placeholder for no display at all
If we drop it, the first method in the list will be automatically loaded.

**Comment by zerline** [comment]
NB: At the moment, the object doc is displayed by default.  Maybe we can suppress that? Then, we can either display a blank page, or display the first method as you seem to suggest (and it will make sense especially if we change the ordering in the methods menu).

**Comment by nthiery** [comment]
>    NB: At the moment, the object doc is displayed by default. Maybe we can
>    suppress that? Then, we can either display a blank page, or display the
>    first method as you seem to suggest (and it will make sense especially
>    if we change the ordering in the methods menu).

Good points.

Let's see. It's nice to see the object documentation by default. Is
there a way to preselect the first entry in the menu (and therefore
not need a dummy entry), but only actually update the right panel when
the user explicitly selects some entry? Alternatively, is it possible
to select '---', while having it be at the bottom of the menu?

**Comment by zerline** [comment]
Having it at the bottom of the menu: yes, for sure, it is possible. But then, you will see (open) the bottom part of the menu instead of the top. That's probably not what you would like. I'll think about that.

**Comment by zerline** [comment]
Committed: https://github.com/sagemath/sage-explorer/commit/f5e876f9583705e1feb171c7dffba7159f042948

**Comment by nthiery** [comment]
I just tested this and it works smoothly. Thank you Odile!
