### ISSUE TITLE
Structure the widget with zone labels

### ISSUE THREAD

**Issue by nthiery** [sagemath/sage-explorer#8]
- [x] Add a **Property** label on top of the list of properties
- [ ] Add a **Methods** label on top of the list of methods
- [ ] Add a **Catalogs** label on top of the list of catalogs (for `explore()`)
- [x] Rename "Main" to "Run" or "Call" in the method tab

**Comment by zerline** [comment]
It's now done, except for Methods/Catalogs, that will wait for the code reengineering (#12)
